services:
  backend:
    image: ghcr.io/swords-line-team/swords-line-backend:latest
    container_name: backend
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    image: ghcr.io/swords-line-team/swords-line-frontend:latest
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
