name: SwordsLine-Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get project version
        id: vars
        run: |
          if git describe --tags --exact-match > /dev/null 2>&1; then
            echo "VERSION=$(git describe --tags --exact-match)" >> $GITHUB_OUTPUT
          else
            echo "VERSION=latest" >> $GITHUB_OUTPUT
          fi

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push backend image
        run: |
          docker build ./backend --file ./backend/Dockerfile --tag ghcr.io/swords-line-team/swords-line-backend:${{ steps.vars.outputs.VERSION }}
          docker push ghcr.io/swords-line-team/swords-line-backend:${{ steps.vars.outputs.VERSION }}

  build-frontend:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get version from previous job
        run: echo "VERSION=${{ needs.build-backend.outputs.version }}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push frontend image
        run: |
          docker build ./frontend --file ./frontend/Dockerfile --tag ghcr.io/swords-line-team/swords-line-frontend:${{ env.VERSION }}
          docker push ghcr.io/swords-line-team/swords-line-frontend:${{ env.VERSION }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - name: Get version from previous job
        run: echo "VERSION=${{ needs.build-backend.outputs.version }}" >> $GITHUB_ENV

      - name: Deploy on prod server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd /home/swords-line-web
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.CR_PAT }}
            docker compose pull
            docker compose up -d
