name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv tool
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.uv/bin" >> $GITHUB_PATH

      - name: Install Commitizen with uv
        run: uv tool install commitizen

      - name: Bump version and generate changelog
        run: cz bump

      - name: Commit version bump and push tags
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "chore(release): bump version"
          git push origin main --follow-tags
