name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Installer Commitizen via uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.uv/bin" >> $GITHUB_PATH
          uv tool install commitizen

      - name: Bump version et générer changelog (non interactif)
        run: |
          cz bump --yes --files-only --changelog

      - name: Commit version bump and push tags
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "chore(release): bump version"
          git push origin main --follow-tags
